exit = ["exit", "quit", "close", "end", "stop", "leave", "bye", "goodbye"]
joke = ["tell me a joke", "tell a joke", "give me a joke", "joke"]
question_start = ["ask me a question", "", "ask a question", "quesion"]
greet = ["hello", "hi", "sup", "whats up"]
question_start2 = ["how are you", "how are you doing", "how are you?", "how are you doing?", "how r u", "how r you", "how are you doing",]
special_word = ["awesome"]
name = ["what is your name", "what's your name", "who are you", "who are you?", "who r u", "who r you"]
sensored = ["fuck you", "nigger", "nigga", "retard", "fuck", "bitch", "shit", "dick"]